In [5]:
pip install dask[dataframe]

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: dask[dataframe] in /home/esierra/.local/lib/python3.11/site-packages (2024.7.1)
Requirement already satisfied: click>=8.1 in /carnegie/hpcdata/software/conda/envs/python-3.11/lib/python3.11/site-packages (from dask[dataframe]) (8.1.7)
Requirement already satisfied: cloudpickle>=1.5.0 in /home/esierra/.local/lib/python3.11/site-packages (from dask[dataframe]) (3.0.0)
Requirement already satisfied: fsspec>=2021.09.0 in /home/esierra/.local/lib/python3.11/site-packages (from dask[dataframe]) (2024.6.0)
Requirement already satisfied: packaging>=20.0 in /home/esierra/.local/lib/python3.11/site-packages (from dask[dataframe]) (24.1)
Requirement already satisfied: partd>=1.4.0 in /home/esierra/.local/lib/python3.11/site-packages (from dask[dataframe]) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /carnegie/hpcdata/software/conda/envs/python-3.11/lib/python3.11/site-packages (from dask[dataframe]) (6.0)
Requirement already satisfied: toolz>=0.10.0 in /home/esierra/.local/lib/python3.11/site-packages (from dask[dataframe]) (0.12.1)
Requirement already satisfied: importlib-metadata>=4.13.0 in /carnegie/hpcdata/software/conda/envs/python-3.11/lib/python3.11/site-packages (from dask[dataframe]) (6.6.0)
Requirement already satisfied: pandas>=2.0 in /carnegie/hpcdata/software/conda/envs/python-3.11/lib/python3.11/site-packages (from dask[dataframe]) (2.2.0)
Collecting dask-expr<1.2,>=1.1 (from dask[dataframe])
  Using cached dask_expr-1.1.9-py3-none-any.whl (241 kB)
Collecting pyarrow>=7.0.0 (from dask-expr<1.2,>=1.1->dask[dataframe])
  Downloading pyarrow-17.0.0-cp311-cp311-manylinux_2_28_x86_64.whl (39.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.9/39.9 MB 15.6 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: zipp>=0.5 in /carnegie/hpcdata/software/conda/envs/python-3.11/lib/python3.11/site-packages (from importlib-metadata>=4.13.0->dask[dataframe]) (3.15.0)
Requirement already satisfied: numpy<2,>=1.23.2 in /carnegie/hpcdata/software/conda/envs/python-3.11/lib/python3.11/site-packages (from pandas>=2.0->dask[dataframe]) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/esierra/.local/lib/python3.11/site-packages (from pandas>=2.0->dask[dataframe]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /carnegie/hpcdata/software/conda/envs/python-3.11/lib/python3.11/site-packages (from pandas>=2.0->dask[dataframe]) (2023.3)
Requirement already satisfied: tzdata>=2022.7 in /carnegie/hpcdata/software/conda/envs/python-3.11/lib/python3.11/site-packages (from pandas>=2.0->dask[dataframe]) (2024.1)
Requirement already satisfied: locket in /home/esierra/.local/lib/python3.11/site-packages (from partd>=1.4.0->dask[dataframe]) (1.0.0)
Requirement already satisfied: six>=1.5 in /carnegie/hpcdata/software/conda/envs/python-3.11/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=2.0->dask[dataframe]) (1.16.0)
Installing collected packages: pyarrow, dask-expr
Successfully installed dask-expr-1.1.9 pyarrow-17.0.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import dask.dataframe as dd
import pandas as pd

In [5]:
states = ['alaska', 'arizona', 'baja_california', 'baja_california_sur', 'british_columbia', 
                  'california', 'nevada', 'oregon', 'sonora', 'washington', 'yukon']
ddf = dd.concat([dd.read_csv(f'../west_coast_dataset/{state_name}/observations_postGL.csv') for state_name in states])
ddf['year'] = dd.to_datetime(ddf['date']).dt.year
ddf['year'].compute()

0        2022
1        2022
2        2020
3        2022
4        2021
         ...
34230    2021
34231    2020
34232    2023
34233    2021
34234    2022
Name: year, Length: 7347727, dtype: int32

In [6]:
train_df = ddf[ddf['supervised'] & 
               (ddf['download_success'] == 'yes') & 
               ((ddf['year'] == 2019) | (ddf['year'] == 2020) | (ddf['year'] == 2021))].compute()
train_df

,state_name,observation_uuid,observer_id_x,latitude,longitude,positional_accuracy,taxon_id,quality_grade,observed_on,ancestry,...,bioclim_17,land_use,supervised,single_image,year,unsupervised_shared,supervised_shared,download_success,observer_id,soil_type
2,alaska,b46d8152-41ce-458c-ab04-d087bcd95221,2229240.0,61.143444,-149.686736,10.0,833536.0,research,2020-08-04,48460/47126/211194/47125/47124/47605/47604/632...,...,0.268671,8,True,True,2020,False,False,yes,NaN,NaN
4,alaska,82cc3ff8-80e1-4ec4-9c59-3008b41a89e6,829451.0,69.625367,-144.679322,10.0,164417.0,research,2021-06-24,48460/47126/211194/47125/47124/48151/50638/840...,...,-0.723336,11,True,False,2021,False,False,yes,NaN,NaN
13,alaska,4bbe7f7b-cf14-4035-8766-e69d7f3ec463,25990.0,57.195700,-135.705313,9.0,76812.0,research,2021-10-09,48460/47126/211194/47125/47124/47181/133387/63...,...,3.186340,6,True,True,2021,True,True,yes,NaN,NaN
30,alaska,812c66c7-0c79-4b6f-85f3-2673630f42b8,805156.0,61.079075,-146.303483,23.0,163269.0,research,2020-06-15,48460/47126/211194/47125/47124/47132/47148/415...,...,0.875547,8,True,False,2020,False,False,yes,NaN,NaN
31,alaska,0d39bd43-f283-4e34-be38-dc7cc118c840,3636655.0,59.435539,-151.179244,10.0,82393.0,research,2021-08-29,48460/47126/211194/47623/47622/47621/764774/82392,...,0.852205,8,True,False,2021,True,True,yes,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34227,yukon,dd83ee78-5ed3-4f18-9b50-bff749930437,NaN,60.878712,-136.939438,24.0,55780.0,research,2021-07-18,48460/47126/211194/47125/47124/47605/47604/632...,...,-0.433905,10,True,False,2021,True,True,yes,1979006.0,3339.0
34229,yukon,b0986317-e3d9-4a3d-afff-ec121fe22328,NaN,61.203495,-139.314713,5.0,167165.0,research,2021-07-26,48460/47126/211194/47125/47124/47181/48932/48933,...,0.298854,16,True,False,2021,False,False,yes,4428761.0,3390.0
34230,yukon,c727f92a-13e7-44e0-84ff-4fd1a9cef1f5,NaN,60.836905,-137.772675,4.0,77780.0,research,2021-07-07,48460/47126/211194/47125/47124/48526/48527/345...,...,-0.343917,1,True,True,2021,True,True,yes,1997119.0,3339.0
34231,yukon,03490afb-ad34-4de2-a2f9-ac19ea1a6e24,NaN,60.723008,-135.052566,28.0,53271.0,research,2020-09-25,48460/47126/211194/47125/47124/71275/47204/147...,...,-0.536749,17,True,True,2020,True,True,yes,2459004.0,7001.0
34233,yukon,b1872544-4c48-4ad9-81da-0298da38aaca,NaN,64.059167,-139.425522,10.0,359560.0,research,2021-07-16,48460/47126/211194/47125/47124/71275/47204/147...,...,-0.536749,6,True,True,2021,False,False,yes,4428761.0,3351.0

In [7]:
states = ['alaska', 'arizona', 'baja_california', 'baja_california_sur', 'british_columbia', 
                  'california', 'nevada', 'oregon', 'sonora', 'washington', 'yukon']
ddf = dd.concat([dd.read_csv(f'../west_coast_dataset/{state_name}/observations_postGL.csv') for state_name in states])
train_df = ddf[ddf['supervised'] & 
               (ddf['download_success'] == 'yes') & 
               ((dd.to_datetime(ddf['date']).dt.year == 2019) | (dd.to_datetime(ddf['date']).dt.year == 2020) | (dd.to_datetime(ddf['date']).dt.year == 2021))].compute()
train_df

,state_name,observation_uuid,observer_id_x,latitude,longitude,positional_accuracy,taxon_id,quality_grade,observed_on,ancestry,...,bioclim_17,land_use,supervised,single_image,year,unsupervised_shared,supervised_shared,download_success,observer_id,soil_type
2,alaska,b46d8152-41ce-458c-ab04-d087bcd95221,2229240.0,61.143444,-149.686736,10.0,833536.0,research,2020-08-04,48460/47126/211194/47125/47124/47605/47604/632...,...,0.268671,8,True,True,2020,False,False,yes,NaN,NaN
4,alaska,82cc3ff8-80e1-4ec4-9c59-3008b41a89e6,829451.0,69.625367,-144.679322,10.0,164417.0,research,2021-06-24,48460/47126/211194/47125/47124/48151/50638/840...,...,-0.723336,11,True,False,2021,False,False,yes,NaN,NaN
13,alaska,4bbe7f7b-cf14-4035-8766-e69d7f3ec463,25990.0,57.195700,-135.705313,9.0,76812.0,research,2021-10-09,48460/47126/211194/47125/47124/47181/133387/63...,...,3.186340,6,True,True,2021,True,True,yes,NaN,NaN
30,alaska,812c66c7-0c79-4b6f-85f3-2673630f42b8,805156.0,61.079075,-146.303483,23.0,163269.0,research,2020-06-15,48460/47126/211194/47125/47124/47132/47148/415...,...,0.875547,8,True,False,2020,False,False,yes,NaN,NaN
31,alaska,0d39bd43-f283-4e34-be38-dc7cc118c840,3636655.0,59.435539,-151.179244,10.0,82393.0,research,2021-08-29,48460/47126/211194/47623/47622/47621/764774/82392,...,0.852205,8,True,False,2021,True,True,yes,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34227,yukon,dd83ee78-5ed3-4f18-9b50-bff749930437,NaN,60.878712,-136.939438,24.0,55780.0,research,2021-07-18,48460/47126/211194/47125/47124/47605/47604/632...,...,-0.433905,10,True,False,2021,True,True,yes,1979006.0,3339.0
34229,yukon,b0986317-e3d9-4a3d-afff-ec121fe22328,NaN,61.203495,-139.314713,5.0,167165.0,research,2021-07-26,48460/47126/211194/47125/47124/47181/48932/48933,...,0.298854,16,True,False,2021,False,False,yes,4428761.0,3390.0
34230,yukon,c727f92a-13e7-44e0-84ff-4fd1a9cef1f5,NaN,60.836905,-137.772675,4.0,77780.0,research,2021-07-07,48460/47126/211194/47125/47124/48526/48527/345...,...,-0.343917,1,True,True,2021,True,True,yes,1997119.0,3339.0
34231,yukon,03490afb-ad34-4de2-a2f9-ac19ea1a6e24,NaN,60.723008,-135.052566,28.0,53271.0,research,2020-09-25,48460/47126/211194/47125/47124/71275/47204/147...,...,-0.536749,17,True,True,2020,True,True,yes,2459004.0,7001.0
34233,yukon,b1872544-4c48-4ad9-81da-0298da38aaca,NaN,64.059167,-139.425522,10.0,359560.0,research,2021-07-16,48460/47126/211194/47125/47124/71275/47204/147...,...,-0.536749,6,True,True,2021,False,False,yes,4428761.0,3351.0